site_name: Henrique Sebastião Wiki
repo_url: https://github.com/henriquesebastiao/wiki
copyright: Henrique Sebastião
theme:
  name: readthedocs
  locale: pt_BR
nav:
  - Início: index.md
  - Desenvolvimento:
      - Git: development/git.md
  - Segurança:
      - GPG: security/gpg.md
      - SSH: security/ssh.md
  - Sistema:
      - Serviços: system/services.md
  - Mikrotik:
      - Certificado: mikrotik/certificate.md
markdown_extensions:
  - toc:
      permalink: true # Links de âncora para cada seção de uma página
